name: Read and Output the content of hello.txt on push to main

on: 
  push:
    branches:
      - main

jobs: 
  read-hello-txt:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout to main
        uses: actions/checkout@v3

      - name: Output hello.txt content
        run: |
          echo "Reading & Outputting contents of hello.txt"
          cat hello.txt

